### ISSUE TITLE
Setting-up the repository

### ISSUE THREAD

**Issue by apelisse** [kubernetes/utils#3]
There are a few things that needs to be done to get this repository up and rolling:
- [ ] Have the root directory fully ready
  - [x] README.md #10 
  - [x] Document how to move a pkg #11
  - [x] Code of conduct #7
  - [x] License #1
  - [ ] Document process? see items below
  - [ ] Issue and pull-request  template
  - [ ] Verify boilerplate
  - [ ] what do I miss here?
- [x] test-infra: let's probably use Travis-ci #4
- [x] Do we need a readme per "package"? `doc.go` should do it.

This is missing a ton, feel free to edit that top-level comment.

**Comment by apelisse** [comment]
cc @pwittrock @thockin @bgrant0607

**Comment by feiskyer** [comment]
Will all [pkg/util](https://github.com/kubernetes/kubernetes/tree/master/pkg/util) be moved here?

**Comment by mengqiy** [comment]
No. Only generic utils (should not depend on k8s types) will be in this repo. Will update README.md soon.
For the rest, we need to find other places.

**Comment by apelisse** [comment]
I think we're mostly good with the set-up. We could have a "verify boilerplate" and issue/pull-requests template but they're not blocking. I'll close that issue.
